### ISSUE TITLE
Crate does not compile without adjusting Cargo.toml

### ISSUE THREAD

**Issue by netthier** [gferon/presage#3]
Due to the following lines at the end of Cargo.toml, this crate will not compile, as the specified directories are nonexistent:
```toml
[patch."https://github.com/Michael-F-Bryan/libsignal-protocol-rs.git"]
libsignal-protocol = { path = "../libsignal-protocol-rs/libsignal-protocol" }

[patch."https://github.com/Michael-F-Bryan/libsignal-service-rs.git"]
libsignal-service = {path = "../libsignal-service-rs/libsignal-service" }
libsignal-service-actix = {path = "../libsignal-service-rs/libsignal-service-actix" }
```

Removing them, and uncommenting the surrounding lines, fixes this issue.
